---
# Run this playbook on the local machine.
- hosts: 127.0.0.1
  connection: local

  vars_prompt: 
    name: ssh_passphrase
    prompt: "Enter ssh passphrase. It will get used if an ssh key needs to be generated"

  vars_files:
    - vars.yml

  tasks:
    - name: Include all tasks
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      loop:
        - tasks/homebrew-packages.yml
        - tasks/security.yml
        - tasks/neovim-osx.yml
        - tasks/ssh.yml
        - tasks/zsh.yml
        - tasks/dotfiles.yml
        - tasks/repos.yml
        - tasks/asdf.yml
        - tasks/asdf_versions.yml
        - tasks/rustup.yml
        - tasks/awscli.yml
        - tasks/coding_helpers.yml

  # handlers:
    # - include: handlers/all.yml
