---
# Run this playbook on the local machine.
- hosts: 127.0.0.1
  connection: local

  vars_prompt: 
    name: ssh_passphrase
    prompt: "Enter ssh passphrase. It will get used if an ssh key needs to be generated"

  vars_files:
    - vars.yml

  tasks:
    - include: tasks/homebrew-packages.yml
    - include: tasks/neovim-osx.yml
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/repos.yml
    - include: tasks/asdf.yml
    - include: tasks/asdf_versions.yml

  # handlers:
    # - include: handlers/all.yml
