#!/usr/bin/env bash

set -e # Exit if any fail
set -o pipefail

export ANSIBLE_NOCOWS=1
export ANSIBLE_STDOUT_CALLBACK=debug
unset ANSIBLE_VAULT_PASSWORD_FILE

unamestr=$(uname)

if [[ "$unamestr" == 'Linux' ]]; then
  echo "## Ubuntu"
  command -v python3 >/dev/null 2>&1 || {
    sudo apt -y install python3
  }

  command -v ansible-playbook >/dev/null 2>&1 || {
    echo Ansible is not installed.
    echo Installing from PPA...
    sudo apt -y update
    sudo apt -y install software-properties-common
    sudo apt-add-repository --yes --update ppa:ansible/ansible
    sudo apt -y install ansible
  }

  # command -v aptitude  >/dev/null 2>&1 || {
  #   echo Aptitude is not installed.
  #   echo Running 'sudo apt-get install aptitude'
  #   sudo apt-get install aptitude
  # }
elif [[ "$unamestr" == "Darwin" ]]; then
  echo "## OSX"
  xcode-select -p 1>/dev/null 2>&1 || {
    echo "XCode CLI tools not yet installed"
    echo "installing"
    sudo xcode-select --install
  }

  # sudo softwareupdate --install-rosetta

  command -v brew >/dev/null 2>&1 || {
    echo Homebrew is not installed.
    echo running the installer...
    # /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  }

  # TODO maybe move brew doctor AFTER the playbook has been run and the dotfiles have been installed
  # brew doctor
  # NOTE Homebrew Cask is now installed as a part of Homebrew install

  command -v ansible-playbook >/dev/null 2>&1 || {
    echo Ansible is not installed.
    echo Installing from Homebrew...
    brew install ansible
  }
  
  # just in case, I had this problem on an older computer
  brew link --overwrite ansible
  # todo echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.zshrc
else
  echo "Unrecognised OS (puter supports only OSX and Ubuntu)"
  exit 1
fi

if [ -z "$1" ]; then
  echo "You must specify a playbook to run"
  echo "   puter ubuntu_desktop.yml"
  exit 1
fi

set -u # Error on unset vars

# TODO lazy install this
# ansible-galaxy collection install community.general

ansible-playbook "$1" -i hosts.ini --ask-become-pass --diff -v --ask-pass
