#!/usr/bin/env bash

set -e # Exit if any fail
set -o pipefail

export ANSIBLE_NOCOWS=1
export ANSIBLE_STDOUT_CALLBACK=debug
unset ANSIBLE_VAULT_PASSWORD_FILE

unamestr=$(uname)

if [[ "$unamestr" == 'Linux' ]]; then
  echo "## Ubuntu"
  command -v python3  >/dev/null 2>&1 || {
    sudo apt -y install python3
  }

  command -v ansible-playbook >/dev/null 2>&1 || {
    echo Ansible is not installed.
    echo Installing from PPA
    sudo apt -y update
    sudo apt -y install software-properties-common
    sudo apt-add-repository --yes --update ppa:ansible/ansible
    sudo apt -y install ansible
  }

  # command -v aptitude  >/dev/null 2>&1 || {
  #   echo Aptitude is not installed.
  #   echo Running 'sudo apt-get install aptitude'
  #   sudo apt-get install aptitude
  # }
elif [[ "$unamestr" == "Darwin" ]]; then
  echo "## OSX"
  xcode-select -p 1>/dev/null;
  rc=$?
  if [[ $rc != 0 ]]; then
    echo "XCode CLI tools not yet installed, installing"
    sudo xcode-select --install
  fi
else
  echo "Unrecognised OS (puter supports only OSX and Ubuntu)"
  exit 1
fi

if [ -z "$1" ]; then
  echo "You must specify a playbook to run"
  echo "   puter ubuntu_desktop.yml"
  exit 1
fi

set -u # Error on unset vars

ansible-playbook "$1" -i hosts.ini --ask-become-pass --diff -v
