---
- hosts: optimal
  remote_user: nietaki

  vars_prompt:
    name: ssh_passphrase
    prompt: "Enter ssh/deluged passphrase"

  vars_files:
    - vars.yml

  tasks:
    - name: check ubuntu codename
      command: "lsb_release -cs"
      register: codename_output
    - name: save the ubuntu codename for other tasks to use
      ansible.builtin.set_fact:
        ubuntu_codename: "{{ codename_output.stdout }}"
    - name: Include all tasks
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      loop:
        - tasks/ubuntu-packages.yml
        - tasks/security.yml
        - tasks/ubuntu-gui-packages.yml
        - tasks/neovim-ubuntu.yml
        - tasks/ssh.yml
        - tasks/zsh.yml
        - tasks/fix_ubuntu_zsh_snaps.yml
        - tasks/dotfiles_readonly.yml
        - tasks/asdf.yml
        - tasks/tmux.yml
        - tasks/plex_server.yml
        - tasks/deluged.yml

  # handlers:
    # - include: handlers/all.yml
