---
# Run this playbook on the local machine.
- hosts: 127.0.0.1
  connection: local

  vars_prompt: 
    name: ssh_passphrase
    prompt: "Enter ssh passphrase. It will get used if an ssh key needs to be generated"

  vars_files:
    - vars.yml

  tasks:
    - include: tasks/ssh.yml
    - include: tasks/ubuntu-packages.yml
    - include: tasks/security.yml
    - include: tasks/ubuntu-gui-packages.yml
    - include: tasks/docker_ubuntu.yml
    - include: tasks/neovim-ubuntu.yml
    - include: tasks/zsh.yml
    - include: tasks/youtube-dl-ubuntu.yml
    - include: tasks/fix_ubuntu_zsh_snaps.yml
    - include: tasks/dotfiles.yml
    - include: tasks/repos.yml
    # - include: tasks/gcp-sdk.yml
    # - include: tasks/heroku.yml
    # - include: tasks/fpp.yml

## commented out to use rtx instead of asdf
    # - include: tasks/asdf.yml
    # - include: tasks/asdf_versions.yml

    # - include: tasks/flutter.yml
    - include: tasks/awscli.yml
    - include: tasks/rustup.yml
    # - include: tasks/aws-vault-ubuntu.yml
    - include: tasks/coding_helpers.yml
    # - include: tasks/elm.yml
    # - include: tasks/rebar3.yml
    # - include: tasks/fish.yml
    # - include: tasks/stack.yml
    # - include: tasks/docker.yml
    # - include: tasks/fzf.yml
    # - include: tasks/k9s.yml
    - include: tasks/platformio.yml
    # - include: tasks/ccls.yml

  # handlers:
    # - include: handlers/all.yml
