---
- hosts: optimal
  remote_user: nietaki

  vars_prompt:
    name: ssh_passphrase
    prompt: "Enter ssh/deluged passphrase"

  vars_files:
    - vars.yml

  tasks:
    - include: tasks/ubuntu-packages.yml
    - include: tasks/security.yml
    - include: tasks/ubuntu-gui-packages.yml
    - include: tasks/neovim-ubuntu.yml
    - include: tasks/ssh.yml
    - include: tasks/zsh.yml
    - include: tasks/fix_ubuntu_zsh_snaps.yml
    - include: tasks/dotfiles_readonly.yml
    - include: tasks/asdf.yml
    - include: tasks/plex_server.yml
    - include: tasks/deluged.yml

  # handlers:
    # - include: handlers/all.yml
