- name: Install some asdf configurations
  # a hack to make node install work a bit better
  shell: PATH="$HOME/.asdf/bin:$PATH" ~/.asdf/bin/asdf install {{ item['plugin'] }} {{ item['version'] }}
  with_items:
    - plugin: erlang
      version: "21.2"
    - plugin: elixir
      version: 1.7.4-otp-21
    # TODO resolve OSX openssl-related errors to reenable this
    # - plugin: rebar
    #   version: 3.12.0
    - plugin: nodejs
      version: 13.6.0
    - plugin: python
      version: 3.7.6
    - plugin: python
      version: 2.7.17
    - plugin: ruby
      version: 2.7.0
    - plugin: ruby
      version: 2.4.7
    - plugin: elixir 
      version: 1.9.1-otp-22
    - plugin: erlang
      version: 22.0.5
    - plugin: elixir 
      version: 1.7.4-otp-20
    # - plugin: erlang
    #   version: 20.3.8.23
    - plugin: kubectl 
      version: 1.17.2

- name: reshim asdf executables, just in case
  shell: ~/.asdf/bin/asdf reshim {{ item }}
  with_items:
    - erlang
    - elixir
    - nodejs
    - python
    - ruby

