- name: install prettier node package
  shell: npm install --global prettier
  ignore_errors: yes

- name: install neovim node package
  shell: npm install --global neovim
  ignore_errors: yes

- name: install neovim ruby package
  shell: gem install neovim
  ignore_errors: yes

- name: override elixir_ls tool versions
  file:
    path: ~/repos/elixir-ls/.tool-versions
    state: absent

- name: prepare elixir_ls
  shell: mix local.rebar --force && mix local.hex --force
  args:
    chdir: ~/repos/elixir-ls
  ignore_errors: yes

- name: compile elixir_ls
  shell: mix deps.get && mix compile
  args:
    chdir: ~/repos/elixir-ls
  ignore_errors: yes

- name: release elixir_ls
  shell: mix elixir_ls.release -o ~/repos/elixir-ls
  args:
    chdir: ~/repos/elixir-ls
  ignore_errors: yes

- name: fix weird behaviour of my environment ¯\_(ツ)_/¯
  replace:
    dest: ~/repos/elixir-ls/language_server.sh
    regexp: '^([^#\n].*asdf/asdf\.sh.*)$'
    replace: '# \1'
  ignore_errors: yes

- name: add aws profile env var in the fresha repos dir
  lineinfile:
    dest: ~/repos/fresha/.envrc
    line: export AWS_PROFILE="shedul-developer"
    create: yes

- name: purge the cached zsh completions to regenerate them
  shell: rm -rf ~/.zcompdump*
  args:
    warn: false

