# Neovim / general
- name: install prettier node package
  shell: npm install --global prettier
  ignore_errors: yes

- name: install neovim node package
  shell: npm install --global neovim
  ignore_errors: yes

- name: install neovim ruby package
  shell: gem install neovim
  ignore_errors: yes

# # Fresha
# - name: add aws profile env var in the fresha repos dir
#   lineinfile:
#     dest: ~/repos/fresha/.envrc
#     line: export AWS_PROFILE="shedul-developer"
#     create: yes

# ZSH
- name: purge the cached zsh completions to regenerate them
  shell: rm -rf ~/.zcompdump*
  ## this was removed in new ansible
  # args:
  #   warn: false

