- set_fact:
    deluge_home: /var/lib/deluge

# https://deluge.readthedocs.io/en/latest/how-to/systemd-service.html
# https://dev.deluge-torrent.org/wiki/UserGuide/ThinClient
- name: create the media group
  group:
    name: media
    system: yes
  become: true

- name: create the deluge user
  user:
    name: deluge
    system: yes
    comment: "Deluge Service"
    password_lock: yes
    group: media
    home: "{{ deluge_home }}"
  become: true

- name: add main user to the media group
  user:
    name: "{{ username }}"
    groups: "media"
    append: true
  become: true

- name: add plex user to the media group
  user:
    name: plex
    groups: "media"
    append: true
  become: true

- name: copy deluged.service file to the server
  copy: 
    src: files/deluge/deluged.service
    dest: /etc/systemd/system/deluged.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: create /etc/systemd/system/deluged.service.d/ directory
  file:
    path: /etc/systemd/system/deluged.service.d/
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true

- name: copy deluge user.conf file to the server
  copy: 
    src: files/deluge/user.conf
    dest: /etc/systemd/system/deluged.service.d/user.conf
    owner: root
    group: root
    mode: '0644'
  become: true

- name: create /srv/torrents directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0770'
    owner: deluge
    group: media
  become: true
  with_items:
    - /srv/torrents
    - /srv/torrents/downloading
    - /srv/torrents/torrent_files
    - /srv/torrents/finished
    - /srv/torrents/finished/movies
    - /srv/torrents/finished/tv
    - /srv/torrents/finished/other

- name: start deluged to create config files
  service:
    name: deluged
    state: started
  become: true

- name: wait for deluge config to get created
  wait_for:
    path: "{{ deluge_home }}/.config/deluge/core.conf"
  become: true

- name: stop deluged
  service:
    name: deluged
    state: stopped
  become: true

- name: allow remote connections to deluge
  lineinfile:
    path: "{{ deluge_home }}/.config/deluge/core.conf"
    line: '"allow_remote": true,'
    regexp: 'allow_remote'
    create: no
  become: true

- name: configure deluge user
  lineinfile:
    path: "{{ deluge_home }}/.config/deluge/auth"
    line: "{{ username }}:{{ ssh_passphrase }}:10"
    regexp: "{{ username }}"
    create: no
  become: true

- name: start deluged for good
  service:
    name: deluged
    state: started
  become: true
