- name: Download Docker dmg 
  get_url:
    url: https://desktop.docker.com/mac/main/arm64/Docker.dmg
    dest: ~/Downloads/Docker.dmg
    mode: 0700

- name: detach the docker just in case it's there
  shell: hdiutil detach /Volumes/Docker
  ignore_errors: yes

- name: attach the docker volume for install
  shell: hdiutil attach ~/Downloads/Docker.dmg

- name: install Docker from cli
  shell: /Volumes/Docker/Docker.app/Contents/MacOS/install --accept-license
  become: true

- name: detach the docker volume after install
  shell: hdiutil detach /Volumes/Docker
  ignore_errors: yes
