- name: check the fedora version
  shell: rpm -E %fedora
  register: fedora_version_output

- name: save the fedora version for other tasks to use
  ansible.builtin.set_fact:
    fedora_version: "{{ fedora_version_output.stdout }}"

- name: install rpmfusion-free repo
  become: true
  command: 'dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm'
  args:
    creates: /etc/yum.repos.d/rpmfusion-free.repo

- name: install rpmfusion-nonfree repo
  become: true
  command: 'dnf install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm'
  args:
    creates: /etc/yum.repos.d/rpmfusion-nonfree.repo

- name: install freeworld codecs
  become: true
  dnf:
    state: latest
    name: libavcodec-freeworld
