- name: create ~/bin directory for future use
  file:
    path: ~/bin
    state: directory
    mode: '0750'

# https://packages.fedoraproject.org/search?query=libgl
- name: Install Fedora CLI packages
  become: true
  dnf:
    state: latest
    name:
      - chromium
      - btop
      - source-foundry-hack-fonts
      - gnome-font-viewer
      # - emacs
      - ack
      - aspell
      - atool
      - autoconf
      - autojump
      # - avahi-utils
      - avahi-tools
      - avahi-ui-tools
      - bless
      # - build-essential
      - '@development-tools'
      - bzip2
      - clang-format
      - cloc
      - clang18
      - cmake
      - cmatrix
      - cowsay
      - curl
      # - deluge-console
      # - deluge-web
      # - deluged
      - direnv
      - dnsutils
      - espeak
      - fd-find
      - flac
      - flatpak
      # - flactag
      - fop
      - fortune
      - fuse
      - fuse-devel
      - gcc
      - g++
      # - gespeaker
      - git
      - git-extras
      - htop
      - httpie
      - inotify-tools
      - jq
      - bzip2
      - bzip2-devel
      - bzip2-libs
      - libevent-devel
      - libffi-devel
      # - libgl1-mesa-dev
      # - libglu1-mesa-dev
      - mesa-libGLU-devel
      - mesa-libGL-devel
      - ncurses
      - ncurses-libs
      - ncurses-devel
      # - libncurses5
      # - libncurses5-dev
      # - libpython2.7
      # - libpython2.7-dev
      - libpng-devel
      - libpq-devel
      - readline-devel
      # - libsqlite3-devel
      - sqlite
      - sqlite-devel
      # - libssh-devel
      - openssl-devel
      - libtool
      - libtool-ltdl-devel
      # - libvips-tools
      - vips
      - vips-devel
      - vips-magick
      # - libxml2-utils
      - libxml2
      - libxml2-devel
      # - lltag
      - llvm
      - m4
      - make
      - man-db
      - mc
      - mediainfo
      - moreutils
      - mpv
      - ncdu
      - net-tools
      - partitionmanager
      - postgresql15
      # - postgresql-client-12
      # - postgresql-client-15
      # - postgresql-15
      - psmisc
      # - python-pip
      # - python3-pip
      # - python3-venv
      - rsync
      - sshuttle
      - the_silver_searcher
      # - software-properties-common
      - shellcheck
      - speedtest-cli
      - spell
      - sqlite3
      - tldr
      - tmux
      - toilet
      - tree
      - units
      # - unixodbc-dev
      - unixODBC-devel
      - unzip
      - vim-enhanced
      - w3m
      # - wamerican
      - wget
      - xsel
      - xsltproc
      # - xz-utils
      - xdotool
      - xz
      - xz-devel
      - xz-libs
      - zeal
      - zsh
      - ripgrep


# # https://clangd.llvm.org/installation.html
# - name: Alternatives link created
#   become: true
#   community.general.alternatives:
#     name: clangd
#     link: /usr/bin/clangd
#     path: /usr/bin/clangd-12
#     priority: 100

# # - name: Install pip3 packages
# #   pip:
# #     executable: pip3
# #     name:
# #       - termtosvg

# # - name: Install cli snap packages
# #   become: true
# #   snap:
# #     name: 
# #       # - youtube-dl
# #       # - shellcheck

# - name: Install Erlang (asdf) dependency packages
#   become: true
#   apt:
#     state: latest
#     name:
#       - autoconf
#       - automake
#       - build-essential
#       - clang
#       - clang-format
#       - clang-tidy
#       - clang-tools
#       - clangd
#       - erlang-wx
#       - fop
#       - libc++-dev
#       - libc++1
#       - libc++abi-dev
#       - libc++abi1
#       - libclang-dev
#       - libclang1
#       - libgl1-mesa-dev
#       - libglu1-mesa-dev
#       - liblldb-dev
#       - libllvm-ocaml-dev
#       - libncurses-dev
#       # - libncurses5-dev
#       - libncurses5-dev
#       - libomp-dev
#       - libomp5
#       - libpng-dev
#       - libssh-dev
#       # - libwxgtk3.0-dev
#       - libwxgtk3.0-gtk3-dev 
#       - libxml2-utils
#       - lld
#       - lldb
#       - llvm
#       - llvm-dev
#       - llvm-runtime
#       - m4
#       - openjdk-11-jdk
#       - python3-clang
#       - unixodbc-dev
#       - xsltproc


# - name: Install Ruby (asdf) dependency packages
#   become: true
#   apt:
#     state: latest
#     name:
#       - autoconf
#       - bison
#       - patch
#       - build-essential
#       - rustc
#       - libssl-dev
#       - libyaml-dev
#       - libreadline6-dev
#       - zlib1g-dev
#       - libgmp-dev
#       - libncurses5-dev
#       - libffi-dev
#       - libgdbm6
#       - libgdbm-dev
#       - libdb-dev
#       - uuid-dev

# - name: Install pandoc/latex and deps
#   become: true
#   apt:
#     state: latest
#     name:
#       - pandoc
#       - texlive-latex-base
#       - texlive-fonts-recommended
#       - texlive-fonts-extra
#       - texlive-latex-extra
#       - wkhtmltopdf

# - name: Install some asdf / python prequisites
#   become: true
#   apt:
#     state: latest
#     name:
#       - build-essential
#       - libssl-dev
#       - zlib1g-dev
#       - libbz2-dev
#       - libreadline-dev
#       - libsqlite3-dev
#       - curl
#       - libncursesw5-dev
#       - xz-utils
#       - tk-dev
#       - libxml2-dev
#       - libxmlsec1-dev
#       - libffi-dev
#       - liblzma-dev
