- name: Install brew apps
  homebrew:
    update_homebrew: yes
    upgrade_all: no
    name: 
      - autoconf
      - ack
      - boost
      - cmatrix
      # - coreutils
      # - csshx
      - direvn
      # - git
      - httpie
      - pygobject3
      - gtk+3
      - adwaita-icon-theme
      - libtorrent-rasterbar
      - midnight-commander
      - ncdu
      - tmux
      - tree
      - unzip
      - jq
      - youtube-dl
      - openssl
      - vim 
      - cmake
      - docker
      # - git-extras
      # - gpg
      # - htop-osx
      # - hub
      # - ispell
      # - libxslt
      # - llvm
      # - midnight-commander
      # # - neovim
      # - openjpeg
      # # - postgresql
      # - pt
      # - ruby
      # - the_silver_searcher 
      # - tintin
      # - unar
      # - unixodbc
      # - vim
      # - wget
      # - wxmac
      # - zsh

- name: Install brew cask apps
  homebrew_cask:
    state: present
    accept_external_apps: yes
    sudo_password: {{ ansible_become_pass }}
    upgrade: yes
    name:
      # - dropbox
      # - skim
      # - skype
      - adobe-acrobat-reader
      - adoptopenjdk
      - bettertouchtool
      - brave-browser
      - dash
      - datagrip
      - deluge
      - firefox
      - flux
      - google-chrome
      - hex-fiend
      - iterm2
      - java11
      - karabiner-elements
      - kindle
      - libreoffice
      - ngrok
      - postman
      - slack
      - sourcetree
      - spotify
      - steam
      - sublime-text
      - suspicious-package
      - telegram
      - texmaker
      - texshop
      - textmate
      - unetbootin
      - visual-studio-code
      - vlc
      - whatsapp
