# needs interactive terminal, move to puter
#- name: install rosetta stone
#  shell: softwareupdate --install-rosetta
#  become: true

- name: Uninstall brew awscli
  homebrew:
    upgrade_all: no
    state: absent
    name:
      - awscli

- name: Install brew apps
  homebrew:
    # update_homebrew: yes
    upgrade_all: no
    state: present # linked
    name: 
      # - csshx
      # - docker # let's see what the correct way is
      # - ispell
      # - neovim # separately
      # - postgresql
      - ack
      - aspell
      - autoconf
      - boost
      - cmake
      - cmatrix
      - coreutils
      - direnv
      - ffmpeg
      - git
      - git-extras
      - gnu-units
      - gpg
      - gtk+3
      - htop-osx
      - httpie
      - hub
      - imagemagick
      - jq
      - lame
      - libsodium
      - libtorrent-rasterbar
      - libxslt
      - llvm
      - midnight-commander
      - ncdu
      - openjpeg
      - openssl
      - pt
      - pygobject3
      - ruby
      - ssh-copy-id
      - the_silver_searcher
      - tintin
      - tmux
      - tree
      - unar
      - unixodbc
      - unzip
      - vim
      - wget
      # - wxmac
      - youtube-dl
      - zsh
      - shellcheck
      - sshuttle
      - bash

- name: Install brew cask apps
  homebrew_cask:
    state: present
    accept_external_apps: yes
    # sudo_password: "{{ ansible_become_pass }}"
    upgrade: no
    name:
      # - dropbox
      # - skim
      # - skype
      - adobe-acrobat-reader
      - adoptopenjdk
      - bettertouchtool
      - brave-browser
      - dash
      - datagrip
      - deluge
      - firefox
      - flux
      - google-chrome
      - hex-fiend
      - iterm2
      # - java11
      - karabiner-elements
      - kindle
      - libreoffice
      - postman
      - slack
      - sourcetree
      - spotify
      - steam
      - sublime-text
      - suspicious-package
      - telegram
      - texmaker
      - texshop
      - textmate
      - unetbootin
      - visual-studio-code
      - vlc
      - whatsapp
      - rectangle
      - zoom
