- name: install packages
  apt: name={{ item }} state=latest
  become: true
  with_items:
    - chromium
    - clipit
    - feh
    - fonts-dejavu
    - fonts-roboto
    - gnome-brave-icon-theme
    - gnome-colors
    - i3
    - iceweasel
    - mupdf
    - rxvt-unicode-256color
    - unclutter
    - xbacklight
    - xorg

- alternatives:
  args:
    name: x-terminal-emulator
    path: /usr/bin/urxvt
  become: true
