- name: Create Neovim dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items:
    - ~/.config/nvim/autoload

- name: Install neovim from Homebrew
  homebrew:
    upgrade_all: no
    # state: linked
    name: 
      - neovim

- name: Install Plug vim package manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.config/nvim/autoload/plug.vim
    mode: 0600

- name: Install python3 neovim lib
  pip:
    name: neovim
    executable: pip3
  ignore_errors: yes

- name: Install python2 neovim lib
  pip:
    name: neovim
    executable: pip2
  ignore_errors: yes
