- name: Create personal temp directory if doesn't exist
  file:
    path: ~/tmp/
    state: directory
    mode: '0755'

- name: download get-platformio.py
  get_url:
    url: https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
    dest: ~/tmp/get-platformio.py

- name: run get-platformio.py
  command: python3 get-platformio.py
  args:
    chdir: ~/tmp
    creates: ~/.platformio/penv/bin/platformio

- name: download platformio udev rules
  get_url:
    url: https://raw.githubusercontent.com/platformio/platformio-core/develop/platformio/assets/system/99-platformio-udev.rules
    # url: https://raw.githubusercontent.com/platformio/platformio-core/master/scripts/99-platformio-udev.rules
    dest: /etc/udev/rules.d/99-platformio-udev.rules
    force: yes
    owner: root
    mode: '644'
  become: true

- name: add main user to the media group
  user:
    name: "{{ username }}"
    groups: dialout,plugdev
    append: true
  become: true

- name: restart udev
  service:
    name: udev
    state: restarted
  become: true
