- name: add plex apt repository
  lineinfile:
    dest: /etc/apt/sources.list.d/plexmediaserver.list
    line: "deb https://downloads.plex.tv/repo/deb public main"
    create: yes
  become: true

- name: add plex key from the server
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
  become: true

- name: Update apt cache
  apt:
    update_cache: true
  become: true

- name: install plex media server
  become: true
  apt:
    state: latest
    name: plexmediaserver
    update_cache: yes

# TODO start  Created symlink /etc/systemd/system/multi-user.target.wants/plexmediaserver.service -> /lib/systemd/system/plexmediaserver.service.
- name: (auto)start plex media server service
  systemd:
    enabled: yes
    state: started
    name: plexmediaserver.service





