- name: Install rebar3 packages
  apt:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - erlang-ssl
    - erlang-asn1
    - erlang-inets
    - erlang-public-key

- name: Install rebar3
  shell: |
    wget https://s3.amazonaws.com/rebar3/rebar3
     chmod +x rebar3
    ./rebar3 local install
    rm -v rebar3
  args:
    chdir: /tmp
    creates: ~/.cache/rebar3/bin/rebar3
