- name: Fetch git repos
  git:
    repo: "{{ item['url'] }}"
    dest: "~/repos/{{ item['path'] }}"
    update: false
  with_items:
    # projects
    - url: git@github.com:nietaki/hokime.git
      path: hokime
    - url: git@github.com:nietaki/rexbug.git
      path: rexbug
    - url: git@github.com:nietaki/orange.git
      path: orange
    - url: git@github.com:nietaki/air_quality_monitor_jacek.git
      path: air_quality_monitor_jacek
    - url: git@github.com:nietaki/stranger_things_lights.git
      path: stranger_things_lights
    - url: git@github.com:nietaki/nietaki.github.io.git
      path: nietaki.github.io
    # Gleam
    - url: git@github.com:gleam-lang/gleam.git
      path: gleam
    # Configs, dotfiles, utis
    - url: git@github.com:nietaki/puter.git
      path: puter
    # Elixir stuff
    - url: git@github.com:elixir-lsp/elixir-ls.git
      path: elixir-ls
    # Fresha stuff
    - url: git@github.com:surgeventures/system.git
      path: fresha/system
    - url: git@github.com:surgeventures/infrastructure.git
      path: fresha/infrastructure
    - url: git@github.com:surgeventures/provisioning.git
      path: fresha/provisioning
