- name: create ~/bin directory for future use
  file:
    path: ~/bin
    state: directory
    mode: '0750'

- name: Install erlang prereqs
  homebrew:
    upgrade_all: no
    state: present
    name: 
      - autoconf
      - openssl@1.1
      - wxwidgets
      - libxslt
      - fop

- name: Download rtx executable
  get_url:
    url: https://rtx.pub/rtx-latest-macos-arm64
    dest: ~/bin/rtx
    mode: 0750

- name: make sure rtx is activated in zsh
  lineinfile:
    path: "~/.zshrc"
    line: 'eval "$(rtx activate zsh)"'
    regexp: 'rtx activate'
    create: true

- name: make sure rtx is activated in bash
  lineinfile:
    path: "~/.bashrc"
    line: 'eval "$(rtx activate bash)"'
    regexp: 'rtx activate'
    create: true
