- name: create ~/bin directory for future use
  file:
    path: ~/bin
    state: directory
    mode: '0750'

- name: Add Postgres signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true

- name: add the postgres source list file
  file:
    path: "/etc/apt/sources.list.d/pgdg.list"
    state: touch
    owner: root
    group: root
  become: true

- name: add the postgres source list entry
  lineinfile:
    path: "/etc/apt/sources.list.d/pgdg.list"
    line: 'deb http://apt.postgresql.org/pub/repos/apt {{ ubuntu_codename }}-pgdg main'
    regexp: 'postgresql'
    create: no
  become: true

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 60
  become: true

- name: Remove Deluge PPA repository
  apt_repository:
    repo: ppa:deluge-team/stable
    update_cache: no
    state: absent
  become: true

# - name: Add Postgres PPA
#   apt_repository:
#     repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ubuntu_codename }} main"
#     update_cache: yes
#     state: present
#   become: true


# TODO check if this is safe on KDE Neon or if we should use pkcon 
# - name: Upgrade all apt packages
#   apt:
#     upgrade: safe
#   become: true

- name: Install Ubuntu CLI packages
  become: true
  apt:
    state: latest
    name:
      # - emacs
      - ack
      - aspell
      - atool
      - autoconf
      - autojump
      - bless
      - build-essential
      - bzip2
      - clang-format
      - cloc
      # - clangd-10
      - cmake
      - cmatrix
      - cowsay
      - curl
      - deluge-console
      - deluge-web
      - deluged
      - direnv
      - dnsutils
      - espeak
      - flac
      - flactag
      - fop
      - fortune
      - fuse
      - gcc
      # - gespeaker
      - git
      - git-extras
      - htop
      - httpie
      - inotify-tools
      - jq
      - libbz2-dev
      - libevent-dev
      - libffi-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libncurses5-dev
      - libpng-dev 
      - libpq-dev 
      - libreadline-dev
      - libsqlite3-dev
      - libssh-dev
      - libssl-dev
      - libtool-bin
      - libvips-tools
      - libxml2-utils
      - lltag
      - llvm
      - m4
      - make
      - man-db
      - mc
      - mediainfo
      - moreutils
      - mpv
      - ncdu
      - net-tools
      - partitionmanager
      # - postgresql-client
      - postgresql-client-12
      - psmisc
      # - python-pip
      - python3-pip
      - rsync
      - sshuttle
      - silversearcher-ag
      - software-properties-common
      - speedtest-cli
      - spell
      - sqlite3
      - tldr
      - tmux
      - toilet
      - tree
      - units
      - unixodbc-dev
      - unzip
      - vim-nox
      - w3m
      - wamerican
      - wget
      - xsel
      - xsltproc
      - xz-utils
      - zeal
      - zsh

- name: RipGrep from .deb
  become: true
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/12.0.0/ripgrep_12.0.0_amd64.deb

- name: Remove some packages that should be installed not via apt
  become: true
  apt:
    state: absent
    name:
      - python-neovim
      - python3-neovim
      - youtube-dl

# - name: Install pip3 packages
#   pip:
#     executable: pip3
#     name:
#       - termtosvg

- name: Install cli snap packages
  become: true
  snap:
    name: 
      - youtube-dl
      - shellcheck

- name: Install Erlang (asdf) dependency packages
  apt:
    name:
      - autoconf
      - build-essential
      - erlang-wx
      - fop
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      # - libncurses5-dev
      - libncurses-dev
      - libpng-dev
      - libssh-dev
      - m4
      - unixodbc-dev
      - xsltproc
      # - libwxgtk3.0-dev
      - libwxgtk3.0-gtk3-dev 
      - libxml2-utils
      - openjdk-11-jdk
    state: latest
  become: true
