- name: Add Deluge PPA repository
  apt_repository:
    repo: ppa:deluge-team/stable
    update_cache: yes
    state: absent
  become: true

- name: Install apt packages
  become: true
  apt:
    state: latest
    name:
      - deluge # it's deluged deluge-web and deluge-console for headless
      - filezilla
      - wxmaxima
      - libreoffice-plasma
      - libreoffice

- name: Install DataGrip from Snap
  become: true
  snap:
    name: datagrip
    classic: yes

- name: Install Slack from Snap
  become: true
  snap:
    name: slack
    classic: yes

# - name: Install VS Code from Snap
#   become: true
#   snap:
#     name: code
#     classic: yes

- name: Install Google Chrome from .deb
  become: true
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

# spt is spotify-tui
- name: Install other desktop apps from Snap
  become: true
  snap:
    name:
      - vlc
      # - spotify
      # - libreoffice
      - opera
      # - standard-notes
      # maybe docker?

- name: add spotify gpg key
  apt_key:
    url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
    state: present
  become: true

- name: add the spotify source list file
  file:
    path: "/etc/apt/sources.list.d/spotify.list"
    state: touch
    owner: root
    group: root
  become: true

- name: add the spotify source list entry
  lineinfile:
    path: "/etc/apt/sources.list.d/spotify.list"
    line: 'deb http://repository.spotify.com stable non-free'
    regexp: 'spotify'
    create: no
  become: true

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 60
  become: true

- name: Install Spotify
  become: true
  apt:
    state: latest
    name:
      - spotify-client
