# - name: Add Deluge PPA repository
#   apt_repository:
#     repo: ppa:deluge-team/stable
#     update_cache: yes
#     state: absent
#   become: true

- name: Install apt packages
  become: true
  apt:
    state: latest
    name:
      # for dpkg get selections
      - debconf-utils
      # - gnome-software-plugin-flatpak
      - filezilla
      - firefox
      - flatpak
      - libreoffice
      - libreoffice-plasma
      - simplescreenrecorder
      - wireshark
      - wxmaxima
      - xdg-desktop-portal

- name: Allow wireshark for non-root users
  become: true
  ansible.builtin.debconf: 
    name: wireshark-common 
    question: wireshark-common/install-setuid
    value: 'true'
    vtype: boolean

- name: apply wireshark config
  become: true
  command: dpkg-reconfigure -f noninteractive wireshark-common

- name: Add user to wireshark group
  user:
    name: "{{ username }}"
    groups: wireshark
    append: yes
  become: true
  ignore_errors: yes

- name: Install DataGrip from Snap
  become: true
  snap:
    name: datagrip
    classic: yes

# - name: Install Slack from Snap
#   become: true
#   snap:
#     name: slack
#     classic: yes

# - name: Install VS Code from Snap
#   become: true
#   snap:
#     name: code
#     classic: yes

- name: Install Google Chrome from .deb
  become: true
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Install Slack from .deb
  become: true
  apt:
    # deb: https://downloads.slack-edge.com/releases/linux/4.28.171/prod/x64/slack-desktop-4.28.171-amd64.deb
    # deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-4.14.0-amd64.deb
    deb: https://downloads.slack-edge.com/releases/linux/4.29.149/prod/x64/slack-desktop-4.29.149-amd64.deb
  ignore_errors: yes

- name: Install other desktop apps from Snap
  become: true
  snap:
    name:
      - vlc
      # - spotify
      # - libreoffice
      - opera
      # - standard-notes
      # maybe docker?

- name: add new(?) spotify gpg key
  apt_key:
    url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
    state: present
  become: true

- name: add the spotify source list file
  file:
    path: "/etc/apt/sources.list.d/spotify.list"
    state: touch
    owner: root
    group: root
  become: true

- name: add the spotify source list entry
  lineinfile:
    path: "/etc/apt/sources.list.d/spotify.list"
    line: 'deb http://repository.spotify.com stable non-free'
    regexp: 'spotify'
    create: no
  become: true

- name: Update apt cache
  apt:
    update_cache: true
    # cache_valid_time: 60
  become: true

- name: Install Spotify
  become: true
  apt:
    state: latest
    name:
      - spotify-client

- name: Install Telegram from Flatpak
  become: true
  community.general.flatpak:
    name: org.telegram.desktop
    state: present

# https://askubuntu.com/questions/1418203/netflix-on-firefox-the-widevinecdm-plugin-has-crashed/1425488#1425488
- name: fix firefox drm
  lineinfile:
    path: "/etc/apparmor.d/usr.bin.firefox"
    insertafter: "per-user"
    line: '  owner @{HOME}/.{firefox,mozilla}/**/gmp-widevinecdm/*/lib*so m,'
    regexp: 'gmp-widevinecdm'
    create: no
  become: true

- name: reload apparmor rules
  become: true
  command: "apparmor_parser --replace /etc/apparmor.d/usr.bin.firefox"
  ignore_errors: yes
