# this is broken. TODO: fix
- name: Add Deluge PPA repository
  apt_repository:
    repo: ppa:deluge-team/stable
    update_cache: yes
  become: true

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 1800
  become: true

# TODO check if this is safe on KDE Neon or if we should use pkcon 
# - name: Upgrade all apt packages
#   apt:
#     upgrade: safe
#   become: true

- name: Install Ubuntu CLI packages
  become: true
  apt:
    state: latest
    name:
      # - emacs
      - ack
      - aspell
      - atool
      - autoconf
      - autojump
      - bless
      - build-essential
      - bzip2
      - clang-format
      - cloc
      - cmake
      - cmatrix
      - cowsay
      - curl
      - deluge-console
      - deluge-web
      - deluged
      - direnv
      - dnsutils
      - flac
      - flactag
      - fop
      - fortune
      - fuse
      - gcc
      - git
      - git-extras
      - htop
      - httpie
      - inotify-tools
      - jq
      - libbz2-dev
      - libevent-dev
      - libffi-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libncurses5-dev
      - libpng-dev 
      - libreadline-dev
      - libsqlite3-dev
      - libssh-dev
      - libssl-dev
      - libtool-bin
      - libvips-tools
      - libwxgtk3.0-dev
      - lltag
      - llvm
      - m4
      - make
      - man-db
      - mc
      - mediainfo
      - moreutils
      - mpv
      - ncdu
      - net-tools
      - partitionmanager
      - psmisc
      - python-pip
      - python3-pip
      - rsync
      - sshuttle
      - silversearcher-ag
      - software-properties-common
      - speedtest-cli
      - spell
      - sqlite3
      - tldr
      - tmux
      - toilet
      - tree
      - unixodbc-dev
      - unzip
      - vim-nox
      - w3m
      - wamerican
      - wget
      - xsel
      - xsltproc
      - xz-utils
      - zeal
      - zsh

- name: Remove some packages that should be installed not via apt
  become: true
  apt:
    state: absent
    name:
      - python-neovim
      - python3-neovim
      - youtube-dl

# - name: Install pip3 packages
#   pip:
#     executable: pip3
#     name:
#       - termtosvg

- name: Install cli snap packages
  become: true
  snap:
    name: 
      - youtube-dl
      - shellcheck

- name: Install Erlang (asdf) dependency packages
  apt:
    name:
      - autoconf
      - build-essential
      - erlang-wx
      - fop
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libncurses5-dev
      - libpng-dev
      - libssh-dev
      - libwxgtk3.0-dev
      - m4
      - unixodbc-dev
      - xsltproc
    state: latest
  become: true
