- name: create ~/bin directory for future use
  file:
    path: ~/bin
    state: directory
    mode: '0750'

- name: Add Postgres signing key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  become: true

- name: add the postgres source list file
  file:
    path: "/etc/apt/sources.list.d/pgdg.list"
    state: touch
    owner: root
    group: root
  become: true
- name: add the postgres source list entry
  lineinfile:
    path: "/etc/apt/sources.list.d/pgdg.list"
    line: 'deb http://apt.postgresql.org/pub/repos/apt {{ ubuntu_codename }}-pgdg main'
    regexp: 'postgresql'
    create: no
  become: true

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 60
  become: true

- name: Remove Deluge PPA repository
  apt_repository:
    repo: ppa:deluge-team/stable
    update_cache: no
    state: absent
  become: true

# - name: Add Postgres PPA
#   apt_repository:
#     repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ubuntu_codename }} main"
#     update_cache: yes
#     state: present
#   become: true


# TODO check if this is safe on KDE Neon or if we should use pkcon 
# - name: Upgrade all apt packages
#   apt:
#     upgrade: safe
#   become: true

- name: Install Ubuntu CLI packages
  become: true
  apt:
    state: latest
    name:
      # - emacs
      - ack
      - aspell
      - atool
      - autoconf
      - autojump
      - avahi-utils
      - bless
      - build-essential
      - bzip2
      - clang-format
      - cloc
      # - clangd-10
      - clangd-12
      - cmake
      - cmatrix
      - cowsay
      - curl
      - deluge-console
      - deluge-web
      - deluged
      - direnv
      - dnsutils
      - espeak
      - fd-find
      - flac
      - flactag
      - fop
      - fortune
      # used to be fuse
      - fuse3
      - gcc
      # - gespeaker
      - git
      - git-extras
      - htop
      - httpie
      - inotify-tools
      - jq
      - libbz2-dev
      - libevent-dev
      - libffi-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libncurses5
      - libncurses5-dev
      - libpython2.7
      - libpython2.7-dev
      - libpng-dev 
      - libpq-dev 
      - libreadline-dev
      - libsqlite3-dev
      - libssh-dev
      - libssl-dev
      - libtool-bin
      - libvips-tools
      - libxml2-utils
      - lltag
      - llvm
      - m4
      - make
      - man-db
      - mc
      - mediainfo
      - moreutils
      - mpv
      - ncdu
      - net-tools
      - partitionmanager
      # - postgresql-client
      - postgresql-client-12
      - postgresql-client-15
      - postgresql-15
      - psmisc
      # - python-pip
      - python3-pip
      - python3-venv
      - rsync
      - sshuttle
      - silversearcher-ag
      - software-properties-common
      - shellcheck
      - speedtest-cli
      - spell
      - sqlite3
      - tldr
      - tmux
      - toilet
      - tree
      - units
      - unixodbc-dev
      - unzip
      - vim-nox
      - w3m
      - wamerican
      - wget
      - xsel
      - xsltproc
      - xz-utils
      - zeal
      - zsh


- name: RipGrep from .deb
  become: true
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
  ignore_errors: yes

- name: Remove some packages that should be installed not via apt
  become: true
  apt:
    state: absent
    name:
      - python-neovim
      - python3-neovim
      - youtube-dl

# https://clangd.llvm.org/installation.html
- name: Alternatives link created
  become: true
  community.general.alternatives:
    name: clangd
    link: /usr/bin/clangd
    path: /usr/bin/clangd-12
    priority: 100

# - name: Install pip3 packages
#   pip:
#     executable: pip3
#     name:
#       - termtosvg

# - name: Install cli snap packages
#   become: true
#   snap:
#     name: 
#       # - youtube-dl
#       # - shellcheck

- name: Install Erlang (asdf) dependency packages
  become: true
  apt:
    state: latest
    name:
      - autoconf
      - automake
      - build-essential
      - clang
      - clang-format
      - clang-tidy
      - clang-tools
      - clangd
      - erlang-wx
      - fop
      - libc++-dev
      - libc++1
      - libc++abi-dev
      - libc++abi1
      - libclang-dev
      - libclang1
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - liblldb-dev
      - libllvm-ocaml-dev
      - libncurses-dev
      # - libncurses5-dev
      - libncurses5-dev
      - libomp-dev
      - libomp5
      - libpng-dev
      - libssh-dev
      # - libwxgtk3.0-dev
      - libwxgtk3.0-gtk3-dev 
      - libxml2-utils
      - lld
      - lldb
      - llvm
      - llvm-dev
      - llvm-runtime
      - m4
      - openjdk-11-jdk
      - python3-clang
      - unixodbc-dev
      - xsltproc


- name: Install Ruby (asdf) dependency packages
  become: true
  apt:
    state: latest
    name:
      - autoconf
      - bison
      - patch
      - build-essential
      - rustc
      - libssl-dev
      - libyaml-dev
      - libreadline6-dev
      - zlib1g-dev
      - libgmp-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm6
      - libgdbm-dev
      - libdb-dev
      - uuid-dev

- name: Install pandoc/latex and deps
  become: true
  apt:
    state: latest
    name:
      - pandoc
      - texlive-latex-base
      - texlive-fonts-recommended
      - texlive-fonts-extra
      - texlive-latex-extra
      - wkhtmltopdf

- name: Install some asdf / python prequisites
  become: true
  apt:
    state: latest
    name:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
