- name: Install zoom Prereqs
  become: true
  apt:
    update_cache: true
    state: latest
    name:
      - libglib2.0-0
      - libgstreamer-plugins-base1.0-0 
      - libxcb-shape0
      - libxcb-shm0
      - libxcb-xfixes0
      - libxcb-randr0
      - libxcb-image0
      - libfontconfig1
      - libgl1-mesa-glx
      - libxi6
      - libsm6
      - libxrender1
      - libpulse0
      - libxcomposite1
      - libxslt1.1
      - libsqlite3-0
      - libxcb-keysyms1
      - libxcb-xtest0
      - ibus

- name: add zoom pubkey
  apt_key:
    url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
    state: present
  become: true

- name: install zoom from .deb
  become: true
  apt:
    deb: https://zoom.us/client/5.14.7.2928/zoom_amd64.deb
  ignore_errors: yes

