- name: Clone Oh My Zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    update: no

- shell: which zsh
  register: which_zsh

- name: Set zsh as default shell
  command: "chsh -s {{ which_zsh.stdout }} {{ username }}"
  become: true
