- name: Clone Oh My Zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    update: no

- name: Clone antigen
  git:
    repo: https://github.com/zsh-users/antigen.git
    dest: ~/.antigen
    update: no

- shell: which zsh
  register: which_zsh

- name: Set zsh as default shell
  command: "chsh -s {{ which_zsh.stdout }} {{ username }}"
  become: true

- name: Create ~/.oh-my-zsh/functions
  file:
    path: ~/.oh-my-zsh/functions
    state: directory

- name: Create ~/.oh-my-zsh/completions
  file:
    path: ~/.oh-my-zsh/completions
    state: directory
