---
# Run this playbook on the local machine.
- hosts: 127.0.0.1
  connection: local

  # Debian stuff, shouldn't apply
  vars:
    debian_release: stretch

  vars_prompt: 
    name: ssh_passphrase
    prompt: "Enter ssh passphrase. It will get used if an ssh key needs to be generated"

  vars_files:
    - vars.yml

  tasks:
    - include: tasks/ubuntu-packages.yml
    - include: tasks/ubuntu-gui-packages.yml
    - include: tasks/neovim.yml
    - include: tasks/ssh.yml
    - include: tasks/dotfiles.yml
    # - include: tasks/awscli.yml
    # - include: tasks/gcp-sdk.yml
    # - include: tasks/heroku.yml
    # - include: tasks/fpp.yml
    - include: tasks/asdf.yml
    # - include: tasks/rustup.yml
    # - include: tasks/elm.yml
    # - include: tasks/rebar3.yml
    # - include: tasks/fish.yml
    # - include: tasks/stack.yml
    # - include: tasks/docker.yml
    # - include: tasks/fzf.yml
    # - include: tasks/k9s.yml
    # goes last because the ssh key might not be set
    # - include: tasks/src.yml

  # handlers:
    # - include: handlers/all.yml
